package view;

public class Animation {

	private int animationDuration;

	public Animation(int animationDuration) {
		this.animationDuration = animationDuration;
	}

	public void playAnimation() throws Exception {

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");

		Thread.sleep(100);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("			                                              ");
		System.out.println("                    @@@@                                  ");
		System.out.println("                    @@@@@@@                               ");
		System.out.println("                    @@  #@@@@@                            ");
		System.out.println("                    @@#@@@   @@@@                         ");
		System.out.println("                    @@@@        @@@@                      ");
		System.out.println("                    @@             @@@@                   ");
		System.out.println("                    @@             ,,,@@@@                ");
		System.out.println("                    @@@@@@@@@@@@@@@@@@@@@@@               ");
		System.out.println("                    @@                                    ");
		System.out.println("       ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           ");
		System.out.println("        @@@                                /@@            ");
		System.out.println("         @@                                @@             ");
		System.out.println("         @@@         @@@@@@@@             @@@             ");
		System.out.println("          @@     @@@@@@@@@@@@@@@@        @@@@@@@@         ");
		System.out.println("     @@@  @@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                    @@@@                                  ");
		System.out.println("                    @@@@@@@.                              ");
		System.out.println("                    @@  @@@@@@                            ");
		System.out.println("                    @@@@@@   @@@@*                        ");
		System.out.println("                    @@@@        @@@@(                     ");
		System.out.println("                    @@             @@@@*                  ");
		System.out.println("                    @@          .%%%%&@@@@                ");
		System.out.println("                    @@@@@@@@@@@@@@@@@@@@@@@               ");
		System.out.println("                    @@,                                   ");
		System.out.println("       &@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           ");
		System.out.println("        @@@                                %@@            ");
		System.out.println("        (@@                          @@@@@@@@@@@          ");
		System.out.println("         @@@@@@@@@@@@@             @@@@@@@@@@@@@@@&       ");
		System.out.println("        @@@@@@@@@@@@@@@@@@       @@@@@@@@@@@@@@@@@@@      ");
		System.out.println("   ***@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                   @      ");
		System.out.println("                                                   # %    ");
		System.out.println("                     @@@@#                         @ @    ");
		System.out.println("                   @      &@@            %@@@@   ,@@      ");
		System.out.println("                  *  @@@@@ @@@@@@@@@@@@@@@@@@@@@@         ");
		System.out.println("                 @  @@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("                 @ @@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@        ");
		System.out.println("                  @ @@@@@ @@@@@@@@@@@@@@@@@@@@@@@@#       ");
		System.out.println("                   @@   @@@@@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("                          *@@@@@@@@@@@@@@@@@@@@@@@@@      ");
		System.out.println("                          @@ #@@@@@@ @@@@ @@@@@@@@@@@&    ");
		System.out.println("                           @@ @ @@@@@    @  @@@@@@@@@@    ");
		System.out.println("                            @@@@@@ ,  @@  @ @@@@@@@@@@%   ");
		System.out.println("                                  @@@ @   @ @@@@@@@@@@    ");
		System.out.println("                                   @#@@@@ @    @@         ");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("  @                                                       ");
		System.out.println("   #@         @                                           ");
		System.out.println("               @                                          ");
		System.out.println("           @@   @                                         ");
		System.out.println("      @@@@   @@   @@                               @      ");
		System.out.println("    @@@@@@@@    @@                                 # %    ");
		System.out.println("   @@@@@@@@@@        @@@@#                         @ @    ");
		System.out.println("@  @@@@@@@@@@  @@  @      &@@            %@@@@   ,@@      ");
		System.out.println("    *@@@@@@@      *  @@@@@ @@@@@@@@@@@@@@@@@@@@@@         ");
		System.out.println("             @@@ @  @@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("                 @ @@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@        ");
		System.out.println("            ,@@   @ @@@@@ @@@@@@@@@@@@@@@@@@@@@@@@#       ");
		System.out.println("      .@@          @@   @@@@@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("    @                     *@@@@@@@@@@@@@@@@@@@@@@@@@      ");
		System.out.println("   @                      @@ #@@@@@@ @@@@ @@@@@@@@@@@&    ");
		System.out.println("                           @@ @ @@@@@    @  @@@@@@@@@@    ");
		System.out.println("                            @@@@@@ ,  @@  @ @@@@@@@@@@%   ");
		System.out.println("                                  @@@ @   @ @@@@@@@@@@    ");
		System.out.println("                                   @#@@@@ @    @@         ");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("           @                                              ");
		System.out.println("            @                                             ");
		System.out.println("       #@     @                                           ");
		System.out.println("         @      @                                         ");
		System.out.println("      @@@@        @                                @      ");
		System.out.println("    @@@@@@@@                                       # %    ");
		System.out.println("   @@@@@@@@@@  @     @@@@#                         @ @    ");
		System.out.println("   @@@@@@@@@@  @@  @      &@@            %@@@@   ,@@      ");
		System.out.println("    *@@@@@@@      *  @@@@@ @@@@@@@@@@@@@@@@@@@@@@         ");
		System.out.println("                 @  @@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("                 @ @@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@        ");
		System.out.println(" #@@@@@      @@   @ @@@@@ @@@@@@@@@@@@@@@@@@@@@@@@#       ");
		System.out.println("                   @@   @@@@@@@@@@@@@@@@@@@@@@@@@@@       ");
		System.out.println("                          *@@@@@@@@@@@@@@@@@@@@@@@@@      ");
		System.out.println("                          @@ #@@@@@@ @@@@ @@@@@@@@@@@&    ");
		System.out.println("                           @@ @ @@@@@    @  @@@@@@@@@@    ");
		System.out.println("                            @@@@@@ ,  @@  @ @@@@@@@@@@%   ");
		System.out.println("                                  @@@ @   @ @@@@@@@@@@    ");
		System.out.println("                                   @#@@@@ @    @@         ");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("			                                              ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                          @             @ ");
		System.out.println("                                           @            @ ");
		System.out.println("                                            @         @   ");
		System.out.println("                                             @         @  ");
		System.out.println("                                                        % ");
		System.out.println("                                         @              @ ");
		System.out.println("                                          @     @@@@@@   @");
		System.out.println("                             @@            @  @@@@@@@@@   ");
		System.out.println("                                  @@          @@@@@@@@@@  ");
		System.out.println("                                              @@@@@@@@@@  ");
		System.out.println("                                               /@@@@@@@   ");
		System.out.println("                                      ,,                  ");
		System.out.println("                                                        @ ");
		System.out.println("                                                    @     ");
		System.out.println("                                               %@@,       ");
		System.out.println("                                                      @   ");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("			                                              ");
		System.out.println("                                        @                 ");
		System.out.println("                                         @                ");
		System.out.println("                              @                           ");
		System.out.println("                                @         @               ");
		System.out.println("                                                          ");
		System.out.println("                   @@,                           @  @     ");
		System.out.println("                         @@         @@@           @  @    ");
		System.out.println("                                  @@@@@@@@  @       @ @   ");
		System.out.println("                                 @@@@@@@@@    @      @    ");
		System.out.println("                                 @@@@@@@@@@     @      #  ");
		System.out.println("                         @@       @@@@@@@@        @     @ ");
		System.out.println("                                    %&&             @     ");
		System.out.println("                                                      @   ");
		System.out.println("                         ,@@@@@                         @ ");
		System.out.println("                                          @@              ");
		System.out.println("                                               @          ");
		System.out.println("                                   @@@@@@,                ");
		System.out.println("                                                @@@       ");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                   @                                      ");
		System.out.println("                     @          @@    @                   ");
		System.out.println("              @              @     @                      ");
		System.out.println("                              @      @                    ");
		System.out.println("                                @      @     @       %    ");
		System.out.println("    @@@            @@@@@@@        @*     #@   @      @    ");
		System.out.println("                  @@@@@@@@@                 @   @         ");
		System.out.println("                  @@@@@@@@@%                  @       @   ");
		System.out.println("                   @@@@@@@@        @            @     ,   ");
		System.out.println("                    @@@@@             @           @       ");
		System.out.println("                                        @@          @     ");
		System.out.println("                               @@                         ");
		System.out.println("                                    @@        @.          ");
		System.out.println("                           *@@           &       @@       ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                         @@@              ");
		System.out.println("                                                @@        ");
		System.out.println("                                                          ");
		System.out.println("														  ");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("           @                          @                   ");
		System.out.println("             @               @         @                  ");
		System.out.println("    @@@@&                      *@        @                ");
		System.out.println("  @@@@@@@@@                       @       *#              ");
		System.out.println("  @@@@@@@@@         @                @      @             ");
		System.out.println("  @@@@@@@@@          @        @@       @@    *@           ");
		System.out.println("   @@@@@@@@            @          @       @    @          ");
		System.out.println("                                            @    @        ");
		System.out.println("                                              @@   @      ");
		System.out.println("        @@@@,         @                          @  @#    ");
		System.out.println("@@            @@@@@@@@@@@                                 ");
		System.out.println("                               %@@                        ");
		System.out.println("                                     %@*                  ");
		System.out.println("   @@@@@@@@@@@@@@@@@@%                    @               ");
		System.out.println("                             @@@             @            ");
		System.out.println("                                    @@                    ");
		System.out.println("                           ,@@@@@       @@                ");
		System.out.println("                                            @             ");
		System.out.println("                                              @@          ");
		System.out.println("                                                          ");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("   @         @           @                                ");
		System.out.println("              @            @@                             ");
		System.out.println("    @@@@&      @              @               @           ");
		System.out.println("  @@@@@@@@@     @               @#             @          ");
		System.out.println("  @@@@@@@@@       @                @            @         ");
		System.out.println("  @@@@@@@@@                          @           @        ");
		System.out.println("   @@@@@@@@                             @                 ");
		System.out.println("                                 @        @               ");
		System.out.println("             @@@@@@@@              @@       @             ");
		System.out.println("  @%                      @@@                             ");
		System.out.println("                                *@@                   @   ");
		System.out.println("                      %@@@,                            @  ");
		System.out.println("                              @@.                         ");
		System.out.println("             @@@@@       @@@@&     @@                     ");
		System.out.println("       @                        @      @                  ");
		System.out.println("                                                   @@     ");
		System.out.println("                                                          ");
		System.out.println("                  %@@@@@@@@@@@@@,                         ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");

		Thread.sleep(100);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                              			  ");
		System.out.println("                                   @@@@@           	  ");
		System.out.println("                                   @@@@@@         		  ");
		System.out.println("                                   @@@@         		  ");
		System.out.println("                                              			  ");
		System.out.println("                    @@@@                                  ");
		System.out.println("                    @@@@@@@.                              ");
		System.out.println("                    @@  @@@@@@                            ");
		System.out.println("                    @@@@@@   @@@@*                        ");
		System.out.println("                    @@@@        @@@@(                     ");
		System.out.println("                    @@             @@@@*                  ");
		System.out.println("                    @@          .%%%%&@@@@                ");
		System.out.println("                    @@@@@@@@@@@@@@@@@@@@@@@               ");
		System.out.println("                    @@,                                   ");
		System.out.println("       &@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           ");
		System.out.println("        @@@                                %@@            ");
		System.out.println("        (@@                          @@@@@@@@@@@          ");
		System.out.println("         @@@@@@@@@@@@@             @@@@@@@@@@@@@@@&       ");
		System.out.println("        @@@@@@@@@@@@@@@@@@       @@@@@@@@@@@@@@@@@@@      ");
		System.out.println("   ***@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                   @@@@@@@    			  ");
		System.out.println("			                      @@@@@@@@                ");
		System.out.println("                      @@@@@       @@@@@@@@@               ");
		System.out.println("                      @@@@@@@*     @@@@@@@                ");
		System.out.println("                      @@  @@@@@@                          ");
		System.out.println("                     @@@@@@@  @@@@                        ");
		System.out.println("                     @@@@       @@@@                      ");
		System.out.println("                     @@           @@@@                    ");
		System.out.println("                    @@@@@@@         #@@@                  ");
		System.out.println("        @@@.        @@@*@@@@@@@@@@@@@@@@@@                ");
		System.out.println("       #@@@@@@@@@@@@@@@%            ,@@@@@@               ");
		System.out.println("        @@            @@@@@@@@@@@@@@                      ");
		System.out.println("        @@@                       ,@@@@@@@@@@@            ");
		System.out.println("        @@@                                @@@ @@@@@@@    ");
		System.out.println(" @@@@@@@@@@              @@@@@@@@@        @@@@@@@@@@@@@@ @");
		System.out.println("@@@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                               		  ");
		System.out.println("                                 ||              		  ");
		System.out.println("                                 ||              		  ");
		System.out.println("              \\                 ||                 	  ");
		System.out.println("               \\                ||          //    	  ");
		System.out.println("                \\               ||         //    		  ");
		System.out.println("                 \\                        //     		  ");
		System.out.println("      \\          \\            @@        //              ");
		System.out.println("       \\                    @@@@@       //               ");
		System.out.println("        \\                  @@ %@@@     //                ");
		System.out.println("         \\                @@@  @@@@                      ");
		System.out.println("          \\             @@@@@@@ (@@@                     ");
		System.out.println("                       @@@        @@@                     ");
		System.out.println("         @@@@         @@@          @@@                    ");
		System.out.println("         @@ @@@@@    .@@@@@@@       @@@                   ");
		System.out.println("        @@@     .@@@@@@.   @@@@@@@    @@@                 ");
		System.out.println("        @@@          @@@@@@     @@@@@@*@@@                ");
		System.out.println("        @@&               @@@@@%     @@@@@@               ");
		System.out.println("        @@@@,                  @@@@@@@&   @               ");
		System.out.println("     @@@@@@@@@@@@            @@@@@@@@@@@@                 ");
		System.out.println("    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@#     ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("               **               **                   	**");
		System.out.println("                \\              ||                **   // ");
		System.out.println("                 \\             ||               //  //   ");
		System.out.println("   **             \\            ||              //  //	  ");
		System.out.println("    \\             \\           ||             //   //	  ");
		System.out.println("     \\             \\          ||            //   //	  ");
		System.out.println("      \\             \\         ||           //   //	  ");
		System.out.println("       \\             \\        ||          //   // 	  ");
		System.out.println("        \\             \\       ||         //   //		  ");
		System.out.println("         \\             \\                //   //   	  ");
		System.out.println("          \\             \\   @@         //   //          ");
		System.out.println("           \\               @@@@@       //   //           ");
		System.out.println("            \\             @@ %@@@     //   //            ");
		System.out.println("             \\           @@@  @@@@        //             ");
		System.out.println("              **        @@@@@@@ (@@@      //              ");
		System.out.println("                       @@@        @@@                     ");
		System.out.println("         @@@@         @@@          @@@                    ");
		System.out.println("         @@ @@@@@    .@@@@@@@       @@@                   ");
		System.out.println("        @@@     .@@@@@@.   @@@@@@@    @@@                 ");
		System.out.println("        @@@          @@@@@@     @@@@@@*@@@                ");
		System.out.println("        @@&               @@@@@%     @@@@@@               ");
		System.out.println("        @@@@,                  @@@@@@@&   @               ");
		System.out.println("     @@@@@@@@@@@@            @@@@@@@@@@@@                 ");
		System.out.println("    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@#     ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(200);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                **             **               ** 	  ");
		System.out.println("   **            \\            ||              //    	  ");
		System.out.println("    \\            \\           ||             //     	  ");
		System.out.println("     \\            \\          ||            //      	  ");
		System.out.println("      \\            \\         ||           //      	**");
		System.out.println("       \\            \\        ||          //          // ");
		System.out.println("        \\            \\       ||         //          //  ");
		System.out.println("         \\            \\      ||        //          //   ");
		System.out.println("          \\            \\     ||       //          //	  ");
		System.out.println("           \\            \\    ||      //          //	  ");
		System.out.println("            \\            \\          //          //      ");
		System.out.println("             \\                      //          //       ");
		System.out.println("              \\             @@@@   //          //        ");
		System.out.println("               \\           @@@@@@             //         ");
		System.out.println("                \\         @@@  @@@@          //          ");
		System.out.println("                 \\        @@@@@@@@@@@       //           ");
		System.out.println("                         @@@@@     @@@      //            ");
		System.out.println("                        @@         *@@@    //             ");
		System.out.println("           @           @@@@          @@@                  ");
		System.out.println("          @@@@@@@@    @@@@@@@@@@@      @@@                ");
		System.out.println("          @@     @@@@@@@@      @@@@@@@@@@@@@              ");
		System.out.println("  @@@@@@, @@           .@@@@@@@       @@@@@@@             ");
		System.out.println("@@@@@@@@@@@@@                 @@@@@@@(           @@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@          @@@@@@@@@&@@@@@@@  @@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                          @@@                             ");
		System.out.println("                         @@@@@                            ");
		System.out.println("                        @@@ @@@@                          ");
		System.out.println("                        @@ .@@@@@                         ");
		System.out.println("                       @@@@@@   @@@                       ");
		System.out.println("                      @@@#       @@@@                     ");
		System.out.println("                      @@           @@@                    ");
		System.out.println("   @@@@ @@@@@@.      @@@@@@@@        @@@                  ");
		System.out.println("@@@@@@@@@@@# @@@@@@@@@@    @@@@@@@@@  @@@.         &@@@@@@");
		System.out.println("@@@@@@@@@@@@@@      @@@@@@@       @@@@@@@@@      @@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@       @@@@@@@@@@@     @@@#   @@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                               		  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                  @@@                     ");
		System.out.println("                                @@@@@@                    ");
		System.out.println("                               @@@ @@@                    ");
		System.out.println("             @@@             @@@ @@@@@@                   ");
		System.out.println("            @@@@@@         @@@@@@@@@@@@                   ");
		System.out.println("           @@@   @@@@     @@@        @@@                  ");
		System.out.println("          @@@       @@@ @@@@@@        @@&                 ");
		System.out.println("     @@@@@@@@@        @@@@   @@@@@@@  @@@         @@@@    ");
		System.out.println("   @@@@@@@@@@@@@@        @@@*@@@@@@@@@@@@@    @@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@*@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                   @*                     ");
		System.out.println("                                .@@@@                     ");
		System.out.println("                               @@@ @@@                    ");
		System.out.println("             @@              @@@@  @@@                    ");
		System.out.println("            @@@@@@         @@@@@@@@@@@@                   ");
		System.out.println("           @@@   @@@      @@@        @@@        @@@@@@@   ");
		System.out.println("         @@@@@@@@@@@@@/ @@@@@    @@@@@@@   *@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                           @@                             ");
		System.out.println("                          @@@@@                           ");
		System.out.println("                         %@@ @@@                          ");
		System.out.println("                         @@@  @@@@                        ");
		System.out.println("                        @@@@@@@ @@@@     #@@@@@@@@        ");
		System.out.println("@@         @@@@@@@@     @@@@      @@@  @@@@@@@@@@@@@@   #@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@#@@@          @@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                  @@@@                    ");
		System.out.println("                                @@@@@@      @@@@@@@@      ");
		System.out.println("                 %@@@@@@@@     @@@( @@@  @@@@@@@@@@@@@@@* ");
		System.out.println("   @@        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                    @@@@@.                  @@@@@@@@@     ");
		System.out.println("@@@@@          @@@@@@@@@@@@@@             @@@@@@@@@@@@@   ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&     @@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("              %                  @@@@@@@@@                ");
		System.out.println("@@@       @@@@@@@@@@            @@@@@@@@@@@@              ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@    &@@@@@@@@@@@@@@@@@            ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@         ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("@@                @@@@@@                  ,,              ");
		System.out.println("@@@@@         @@@@@@@@@@@@@         @@@@@@@@@@@@@         ");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");

		Thread.sleep(this.animationDuration);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                                          ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");
		System.out.println("                                              			  ");

		Thread.sleep(100);
		new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();

	}

}
